//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptiveProgressStatus) DeepCopyInto(out *AdaptiveProgressStatus) {
	*out = *in
	if in.ActiveSignals != nil {
		in, out := &in.ActiveSignals, &out.ActiveSignals
		*out = make([]Signal, len(*in))
		copy(*out, *in)
	}
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptiveProgressStatus.
func (in *AdaptiveProgressStatus) DeepCopy() *AdaptiveProgressStatus {
	if in == nil {
		return nil
	}
	out := new(AdaptiveProgressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptiveThrottlingConfig) DeepCopyInto(out *AdaptiveThrottlingConfig) {
	*out = *in
	if in.SignalChecks != nil {
		in, out := &in.SignalChecks, &out.SignalChecks
		*out = new(SignalChecksConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptiveThrottlingConfig.
func (in *AdaptiveThrottlingConfig) DeepCopy() *AdaptiveThrottlingConfig {
	if in == nil {
		return nil
	}
	out := new(AdaptiveThrottlingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceLifecyclePolicy) DeepCopyInto(out *NamespaceLifecyclePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceLifecyclePolicy.
func (in *NamespaceLifecyclePolicy) DeepCopy() *NamespaceLifecyclePolicy {
	if in == nil {
		return nil
	}
	out := new(NamespaceLifecyclePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceLifecyclePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceLifecyclePolicyList) DeepCopyInto(out *NamespaceLifecyclePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NamespaceLifecyclePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceLifecyclePolicyList.
func (in *NamespaceLifecyclePolicyList) DeepCopy() *NamespaceLifecyclePolicyList {
	if in == nil {
		return nil
	}
	out := new(NamespaceLifecyclePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceLifecyclePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceLifecyclePolicySpec) DeepCopyInto(out *NamespaceLifecyclePolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(TerminationGracePeriodConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupNodeReadinessPolicy != nil {
		in, out := &in.StartupNodeReadinessPolicy, &out.StartupNodeReadinessPolicy
		*out = new(StartupNodeReadinessPolicy)
		(*in).DeepCopyInto(*out)
	}
	out.ResumeDelay = in.ResumeDelay
	if in.AdaptiveThrottling != nil {
		in, out := &in.AdaptiveThrottling, &out.AdaptiveThrottling
		*out = new(AdaptiveThrottlingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceLifecyclePolicySpec.
func (in *NamespaceLifecyclePolicySpec) DeepCopy() *NamespaceLifecyclePolicySpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceLifecyclePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceLifecyclePolicyStatus) DeepCopyInto(out *NamespaceLifecyclePolicyStatus) {
	*out = *in
	if in.LastStartupAt != nil {
		in, out := &in.LastStartupAt, &out.LastStartupAt
		*out = (*in).DeepCopy()
	}
	if in.LastResumeAt != nil {
		in, out := &in.LastResumeAt, &out.LastResumeAt
		*out = (*in).DeepCopy()
	}
	if in.StartupNodesWaited != nil {
		in, out := &in.StartupNodesWaited, &out.StartupNodesWaited
		*out = new(int32)
		**out = **in
	}
	if in.StartupReadyNodes != nil {
		in, out := &in.StartupReadyNodes, &out.StartupReadyNodes
		*out = new(int32)
		**out = **in
	}
	if in.AdaptiveProgress != nil {
		in, out := &in.AdaptiveProgress, &out.AdaptiveProgress
		*out = new(AdaptiveProgressStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupResumeDelayStartedAt != nil {
		in, out := &in.StartupResumeDelayStartedAt, &out.StartupResumeDelayStartedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceLifecyclePolicyStatus.
func (in *NamespaceLifecyclePolicyStatus) DeepCopy() *NamespaceLifecyclePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceLifecyclePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePressureCheckConfig) DeepCopyInto(out *NodePressureCheckConfig) {
	*out = *in
	if in.PressureTypes != nil {
		in, out := &in.PressureTypes, &out.PressureTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePressureCheckConfig.
func (in *NodePressureCheckConfig) DeepCopy() *NodePressureCheckConfig {
	if in == nil {
		return nil
	}
	out := new(NodePressureCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeReadyCheckConfig) DeepCopyInto(out *NodeReadyCheckConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeReadyCheckConfig.
func (in *NodeReadyCheckConfig) DeepCopy() *NodeReadyCheckConfig {
	if in == nil {
		return nil
	}
	out := new(NodeReadyCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUsageCheckConfig) DeepCopyInto(out *NodeUsageCheckConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUsageCheckConfig.
func (in *NodeUsageCheckConfig) DeepCopy() *NodeUsageCheckConfig {
	if in == nil {
		return nil
	}
	out := new(NodeUsageCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingPodsCheckConfig) DeepCopyInto(out *PendingPodsCheckConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingPodsCheckConfig.
func (in *PendingPodsCheckConfig) DeepCopy() *PendingPodsCheckConfig {
	if in == nil {
		return nil
	}
	out := new(PendingPodsCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Signal) DeepCopyInto(out *Signal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Signal.
func (in *Signal) DeepCopy() *Signal {
	if in == nil {
		return nil
	}
	out := new(Signal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalChecksConfig) DeepCopyInto(out *SignalChecksConfig) {
	*out = *in
	if in.CheckNodeReady != nil {
		in, out := &in.CheckNodeReady, &out.CheckNodeReady
		*out = new(NodeReadyCheckConfig)
		**out = **in
	}
	if in.CheckNodePressure != nil {
		in, out := &in.CheckNodePressure, &out.CheckNodePressure
		*out = new(NodePressureCheckConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CheckPendingPods != nil {
		in, out := &in.CheckPendingPods, &out.CheckPendingPods
		*out = new(PendingPodsCheckConfig)
		**out = **in
	}
	if in.CheckNodeUsage != nil {
		in, out := &in.CheckNodeUsage, &out.CheckNodeUsage
		*out = new(NodeUsageCheckConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalChecksConfig.
func (in *SignalChecksConfig) DeepCopy() *SignalChecksConfig {
	if in == nil {
		return nil
	}
	out := new(SignalChecksConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupNodeReadinessPolicy) DeepCopyInto(out *StartupNodeReadinessPolicy) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupNodeReadinessPolicy.
func (in *StartupNodeReadinessPolicy) DeepCopy() *StartupNodeReadinessPolicy {
	if in == nil {
		return nil
	}
	out := new(StartupNodeReadinessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerminationGracePeriodConfig) DeepCopyInto(out *TerminationGracePeriodConfig) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(int64)
		**out = **in
	}
	if in.StatefulSet != nil {
		in, out := &in.StatefulSet, &out.StatefulSet
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerminationGracePeriodConfig.
func (in *TerminationGracePeriodConfig) DeepCopy() *TerminationGracePeriodConfig {
	if in == nil {
		return nil
	}
	out := new(TerminationGracePeriodConfig)
	in.DeepCopyInto(out)
	return out
}
